"""add_lat_lng_to_events

Revision ID: 4c1488c1636d
Revises: 70d5274ae4f3
Create Date: 2026-02-23 20:25:51.801245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1488c1636d'
down_revision: Union[str, None] = '70d5274ae4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    # ### end Alembic commands ###
