"""add_bank_fields_to_events

Revision ID: 86fa88a3d668
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 08:50:38.373166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fa88a3d668'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('bank_name', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('bank_account_number', sa.String(length=30), nullable=True))
    op.add_column('events', sa.Column('account_holder_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'account_holder_name')
    op.drop_column('events', 'bank_account_number')
    op.drop_column('events', 'bank_name')
    # ### end Alembic commands ###
