"""add_club_id_to_chats

Revision ID: 8790ca1dc4b8
Revises: ce56753652d8
Create Date: 2026-02-25 05:44:26.433895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8790ca1dc4b8'
down_revision: Union[str, None] = 'ce56753652d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('club_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chats_club_id'), 'chats', ['club_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###

    # Backfill: set club_id from event.club_id for existing event chats
    op.execute("""
        UPDATE chats SET club_id = events.club_id
        FROM events
        WHERE chats.event_id = events.id
          AND chats.club_id IS NULL
          AND chats.event_id IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_club_id'), table_name='chats')
    op.drop_column('chats', 'club_id')
    # ### end Alembic commands ###
