"""add parent_id to clubs and role to user_club

Revision ID: c77764783431
Revises: 6ba1e52adea9
Create Date: 2026-02-24 23:30:23.712806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77764783431'
down_revision: Union[str, None] = '6ba1e52adea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'clubs', 'clubs', ['parent_id'], ['id'])
    op.add_column('user_club', sa.Column('role', sa.String(length=20), server_default='member', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_club', 'role')
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'parent_id')
    # ### end Alembic commands ###
