"""add settlement system

Revision ID: ce56753652d8
Revises: c77764783431
Create Date: 2026-02-25 00:35:10.538623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce56753652d8'
down_revision: Union[str, None] = 'c77764783431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum values for split status
    op.execute("ALTER TYPE split_status_enum ADD VALUE IF NOT EXISTS 'sent'")
    op.execute("ALTER TYPE split_status_enum ADD VALUE IF NOT EXISTS 'confirmed'")

    op.add_column('payment_splits', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('payment_splits', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('account_holder_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_holder_name')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_name')
    op.drop_column('payment_splits', 'confirmed_at')
    op.drop_column('payment_splits', 'sent_at')
    # ### end Alembic commands ###
